app/config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/hello', ['controller' => 'Hello', 'action' => 'index']);

    /**
     * Top画面につなげる
     */
    $routes->connect('/top', ['controller' => 'Top', 'action' => 'index']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

app/src/Model/Entity/User.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class User extends Entity {
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
}

app/src/Model/Table/UsersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Table;

class UsersTable extends Table {
public function initialize(array $config) {
        $this->belongsTo('Inputs');
    }
}

app/src/Controller/UsersController.php
<?php
namespace App\Controller;
use App\Form\ContactForm;

class UsersController extends AppController {
    public function initialize() {
    //Controller名
    $name = 'Users';
    //autolayout使用
    $this->viewBuilder()->autoLayout = true;
    //layoutを使用
    $this->viewBuilder()->layout('default');
    }

    public function index() {
        //日本語の曜日配列
        $weekjp = array(
            '日', //0
            '月', //1
            '火', //2
            '水', //3
            '木', //4
            '金', //5
            '土'  //6
        );
        //現在の曜日番号（日:0  月:1  火:2  水:3  木:4  金:5  土:6）を取得
        $weekno = date('w');
        //日本語曜日を出力
        $day = $weekjp[$weekno];
        //出力した日本語曜日をセットする
        $this->set('day', $day);
        $userdata = $this->Users->find('all');
        $this->set('userdata',$userdata);
        $this->set('count', $userdata->count());
    }
    
    public function login(){
    
    }
    
    public function regist() {
        if ($this->request->is('post')) {
            $data = $this->request->data;
            $session = $this->request->session();
            $session->write('data', $data);

            return $this->redirect(['action' => 'registconfirm']);
        }
    }

    public function registconfirm() {
       $session = $this->request->session();
       $data = $session->read('data');
       $this->set('inputs', $data);

       $session->write('data', $data);

       return $this->redirect(['action' => 'registcomp']);
    }

    public function registcomp() {
       $session = $this->request->session();
       $data = $session->read('data');
       if ($this->Users->save($data)) {
           return $this->redirect(['action' => 'login']);
       }
    }
    
    public function resetpass() {

    }

    public function resetpasscomp() {

    }
}

app/src/Template/Users/index.ctp
<div class="link">
    <table>
        <tr>
            <ul id="link_hyo">
                <a href="#" id="a_link1">当サイトについて</a><br>
                <a href="#" id="a_link2">初めての方へ</a><br>
                <a href="#" id="a_link3">ルール</a><br>
                <a href="#" id="a_link4">よくある質問</a><br>
            </ul>
        </tr>
    </table>        
    <div class="count">
        <table>
            <tr>
                <ul id="count_hyo">
                    <p id="count_jikou1">
                        <?=date('Y/m/d ',time()).'('.$day.')' ?>
                    </p>
                    <p id="count_jikou2">あなたは</p>
                    <p id="count_jikou3"><?=$count ?>人目の</p>
                    <p id="count_jikou4">犬好きさんです。</p>
                </ul>
            </tr>
        </table>
    </div>
</div>
<div class="sait_kaisetu">
    <p>ここでは、ワンちゃん大好きの人が愛犬の日常や仕草や自慢などをお話しするサイトになります。<br>
       他のお友達とお話ししたり些細な事でも投稿したい方は<font color="red">掲示板へ</font>をクリ
       ックしてください。<br>
       皆さんで楽しく情報を共有しましょう。<br>
    </p>
</div>
<br><br>
<div class="keijiban_btn">
    <a href="<?php echo $this->Url->build(['controller'=>'Inputs', 'action'=>'index']); ?>">掲示板へ</a><br>
</div>

app/src/Template/Users/login.ctp
<?= $this->Html->css('login.css'); ?>
<?= $this->fetch('css') ?>

<?= $this->Form->create() ?>
<div class="mail_input">
    <?= $this->Form->input('メールアドレス', ['class' => 'mail']) ?>
</div>
<div class="password_input">
    <?= $this->Form->input('パスワード',['class' => 'password']) ?>
</div>
<div class="login_button">
    <?= $this->Form->button('ログイン',['class' => 'login']) ?>
</div>
    <?= $this->Form->end() ?>
<div class="back_button">
    <?= $this->Form->button('戻る',['class' => 'logback', 'onclick' => 'history.back()']); ?>
</div>
<h3 class="nosinki_user">新規登録を行っていない方</h3>
<div class="shinki_btn">
    <a class="shinki_toroku" href="<?= $this->Url->build(['controller'=>'Users', 'action'=>'regist']); ?>">会員登録</a><br>
</div>

<h3 class="nopassword_user">パスワードを忘れた方</h3>
<div class="password_btn">
    <a href="<?= $this->Url->build(['controller'=>'Users', 'action'=>'resetpass']); ?>">パスワードを忘れた場合</a><br>
</div>

app/src/Template/Users/regist.ctp
<?= $this->Html->css('regist.css'); ?>
<?= $this->fetch('css') ?>

<h2 class="regist_title">会員登録情報</h2>
<p class="regist_msg">以下のフォームに必要事項を全て入力ください。<br>
   ログイン時のIDはメールアドレスをご利用ください。</p>

<?= $this->Form->create(); ?>
<div class="regist_name">
    <?= $this->Form->text("nickname", ["label" => 'ニックネーム', 'class' => 'registname']) ?>
</div>
<div class="regist_pass">
    <?= $this->Form->text("password", ["label" => 'パスワード', "type" => "password", 'class' => 'registpass']) ?>
</div>
<div class="regist_mail">
    <?= $this->Form->text("mailaddress", ["label" => 'メールアドレス', 'class' => 'registmail']) ?>
</div>
<?= $this->Form->button('この内容で確認する',['class' => 'resetbutton']) ?>
<?= $this->Form->button('全てクリア',["type" => "reset", 'class' => 'clerabutton']) ?>
<?= $this->Form->end() ?>

app/src/Template/Users/registcomp.ctp
<h2>会員情報登録確認</h2>

<div class="shinki_btn">
    <a class="" href="<?= $this->Url->build(['controller'=>'Users', 'action'=>'']); ?>">完了</a><br>
</div>

app/src/Template/Users/registconfirm.ctp
<h2>会員情報登録確認</h2>

<?= $this->Form->create() ?>
    <?= $inputs['nickname'] ?><br>
    <?= $inputs['password'] ?><br>
    <?= $inputs['mailaddress'] ?>

    <?= $this->Form->button('確認',['class' => 'resetbutton']) ?>
    <?= $this->Form->button('戻る',['class' => 'logback', 'onclick' => 'history.back()']); ?>
<?= $this->Form->end() ?>

app/src/Template/Users/resetpass.ctp
<?= $this->Html->css('resetpass.css'); ?>
<?= $this->fetch('css') ?>

<h2 class="passtitle">パスワード再設定</h2>
<p class="pass_setumei">パスワードを再設定します。<br>
   ニックネーム、メールアドレスは忘れずにご入力下さい。</p>

<?= $this->Form->create() ?>
<div class="passname">
    <?= $this->Form->input('ニックネーム', ['class' => 'nickname']) ?>
</div>
<div class="passmail">
    <?= $this->Form->input('メールアドレス', ['class' => 'pass_mail']) ?>
</div>
<div class="newpassword">
    <?= $this->Form->input("password",["label" => '新しいパスワード', 'class' => 'new_pass']) ?>
</div>
<div class="kakuninpassword">
    <?= $this->Form->input("checkpassword", ["label" => '新しいパスワード確認', 'class' => 'kakunin_pass']) ?>
</div>
<?= $this->Form->button('再設定する',['class' => 'resetbutton']) ?>
<?= $this->Form->end() ?>

app/src/Template/Users/resetpasscomp.ctp
<h2>パスワード再設定完了</h2>

<p>パスワードの設定が完了いたしました。</p>

<div class="comp_btn">
    <a class="complet" href="<?= $this->Url->build(['controller'=>'Users', 'action'=>'login']); ?>">今すぐログインする</a><br>
</div>